---

- block:
    - name: Install Girder system dependencies
      apt:
        name: "{{ item }}"
      with_items:
        - curl
        - git
        - libffi-dev
        - build-essential
        - libjpeg-dev
        - libssl-dev
        - zlib1g-dev
        # Needed for LDAP plugin
        - libsasl2-dev
        - libldap2-dev
  become: yes
  become_user: root
  when: ansible_os_family == "Debian"

- block:
    - name: Install Girder system dependencies
      yum:
        name: "{{ item }}"
      with_items:
        - curl
        - gcc-c++
        - git
        - libffi-devel
        - make
        - openssl-devel
        - libjpeg-turbo-devel
        - zlib-devel
        - openldap-devel
  become: yes
  become_user: root
  when: ansible_os_family == "RedHat"

- name: Download Girder
  git:
    repo: "https://github.com/girder/girder.git"
    dest: "{{ girder_path }}"
    version: "{{ girder_version }}"
    update: "{{ girder_update|default(omit) }}"
    force: "{{ girder_force|default(omit) }}"
    clone: "{{ girder_clone|default(omit) }}"
  register: vc

- set_fact:
    girder_files_updated: "{{ vc.changed }}"
