---

- fail:
    msg="ansible-role-girder only supports Ubuntu Trusty/Xenial and Redhat/CentOS 7."
  when: (ansible_distribution_release != "trusty") and
        (ansible_distribution_release != "xenial") and
        (ansible_os_family == "RedHat" and ansible_distribution_major_version != "7")

- name: Ensure girder base directory exists
  file:
    path: "{{ girder_path }}"
    state: directory
    group: "{{ girder_user|default(ansible_user_id) }}"
    owner: "{{ girder_user|default(ansible_user_id) }}"
    mode: 0755
  become: yes
  become_user: root

- include: npm-RedHat.yml
  when:
    - girder_web
    - ansible_os_family == "RedHat"

- include: npm-Debian.yml
  when:
    - girder_web
    - ansible_os_family == "Debian"

- include: girder.yml

- include: pip.yml

- include: daemon.yml
  when: girder_daemonize

- name: Install Girder Plugins
  command: "{{ girder_virtualenv }}/bin/girder-install plugin {{ item.args|default('') }} {{ item.path|default(item) }}"
  with_items: "{{ girder_plugins }}"

- name: Build Girder (web)
  command: "{{ girder_install_executable }} web {{ girder_web_extra_args }}"
  args:
    chdir: "{{ girder_path }}"
  # ensure that the install is one that uses web assets and
  # the assets are always supposed to be rebuilt, or the files have changed (from git)
  when: girder_web and (girder_always_build_assets or girder_files_updated)
